(in-package :mu-cl-resources)

(define-resource mail ()
  :class (s-prefix "example:Mail")
  :properties `((:sender :string ,(s-prefix "example:sender"))
		(:subject :string ,(s-prefix "example:subject"))
		(:content :string ,(s-prefix "example:content"))
		(:ready :string ,(s-prefix "example:ready")))
  :resource-base (s-url "http://example.com/mails/")
  :on-path "mails")
